apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "{{  .Chart.Name }}-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: http
  {{- if hasKey .Values.service "nodePort" }}
    nodePort: {{ .Values.service.nodePort }}
  {{- end }}
  selector:
    app: "{{  .Chart.Name }}-selector"