# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: codefresh/medium-customer-manager
  tag: 1.0.0
  pullPolicy: IfNotPresent 
service:
  name: Node
  type: NodePort
  servicePort: 3000

config:
  ## Currently only supports file
  type: file
  ## Contents of config in YAML
  content: |-
    window.REACT_APP_CUSTOMER_HOST='https://www.bookmarks.dev/api/public/bookmarks'